version: '3.8'
services:
  api:
    build: ./api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - redis

  frontend:
    build: ./frontend
    ports:
      - "80:80"

  integration:
    build: ./integration
    ports:
      - "4000:4000"
    depends_on:
      - api

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
